modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
#issueTrackerURL="https://github.com/Pdiddy973/AllTheCompressed/issues" #optional
[[mods]] #mandatory
modId="allthecompressed" #mandatory
version="${file.jarVersion}" #mandatory
displayName="AllTheCompressed" #mandatory
#displayURL="https://github.com/Pdiddy973/AllTheCompressed/tree/1.18" #optional
logoFile="AllTheCompressed.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Pdiddy973" #optional
description='''
adds 1-9x compressed versions of blocks, and recipes.
'''
[[dependencies.allthecompressed]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[47,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.allthecompressed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.allthecompressed]]
    modId="alltheores"
    mandatory=false
    versionRange="[2,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.allthecompressed]]
    modId="productivebees"
    mandatory=false
    versionRange="[1.20,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.allthecompressed]]
    modId="supplementaries"
    mandatory=false
    versionRange="[1.20,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.allthecompressed]]
    modId="enderio"
    mandatory=false
    versionRange="[6,)"
    ordering="AFTER"
    side="BOTH"
