# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
license="MIT"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/Pdiddy973/AllTheCompressed/issues"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
# The modid of the mod
modId="allthecompressed"
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="AllTheCompressed" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://github.com/Pdiddy973/AllTheCompressed" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="examplemod.png" #optional
# A text field displayed in the mod UI
authors="Pdiddy973" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
a good description
'''
[[dependencies.allthecompressed]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.allthecompressed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.allthecompressed]]
    modId="alltheores"
    mandatory=true
    versionRange="[1.3.6,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.allthecompressed]]
    modId="allthemodium"
    mandatory=true
    versionRange="[1.5.10,)"
    ordering="BEFORE"
    side="BOTH"
